
GET http://localhost:3000/contacts
Content-Type: application/json




GET http://localhost:3000/contacts/{{682aeddc8c1733eee03ec3dd}}
Content-Type: application/json



### Create a new contact 

POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "jane@example.com",
    "favoriteColor": "Brown",
    "birthday": "1990-01-01"
}




### Update a contact by ID 

PUT http://localhost:3000/contacts/{{682aeddc8c1733eee03ec3dd}}
Content-Type: application/json

{
  "firstName": "Patrick",
  "lastName": "Mukula",
  "email": "patrickkeita80@yahoo.com",
  "favoriteColor": "brown",
  "birthday": "1991/07/09"
}


### Delete a contact by ID for next time

DELETE http://localhost:3000/contacts/{{682aeddc8c1733eee03ec3dd}}
Content-Type: application/json
